name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - type: debug
            cmake_type: Debug

          - type: release
            cmake_type: Release

    steps:
      - name: setup
        run: |
          sudo apt-get -y update
          sudo apt-get -y install \
            build-essential \
            cmake ninja-build

      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: arm-none-eabi-gcc
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '10.3-2021.10'

      - name: configure
        run: |
          cmake -S . -B build/ -DCMAKE_BUILD_TYPE="${{ matrix.cmake_type }}"

      - name: build
        run: |
          cmake --build build/

      - name: upload-artifact
        uses: actions/upload-artifact@v5
        with:
          name: fnirsi_1013d-${{ matrix.type }}
          path: |
            build/fnirsi_1013d_startup/fnirsi_1013d_startup.bin
            build/fnirsi_1013d_scope/fnirsi_1013d_scope.bin
            build/fnirsi_1013d_scope/fnirsi_1013d.bin
          if-no-files-found: error
